### ISSUE TITLE
[Comick] Can't change uploader list under "Uploaders settings"

### ISSUE THREAD

**Issue by tejassharma96** [xOnlyFadi/xonlyfadi-extensions#17]
When I try to change my uploader blocklist for Comick, I see the following error pop up:
```
Error [PaperbackError(300)] JSError Error: Invalid type for key options; expected `Array<String>` got `Optional<JSValue>` - @[native code]
@:9888:44
```
This was working previously, not sure what changed. I'm on paperback v0.8.7-r12

**Comment by Ivanmatthew** [comment]
> When I try to change my uploader blocklist for Comick, I see the following error pop up:
> 
> ```
> Error [PaperbackError(300)] JSError Error: Invalid type for key options; expected `Array<String>` got `Optional<JSValue>` - @[native code]
> @:9888:44
> ```
> 
> This was working previously, not sure what changed. I'm on paperback v0.8.7-r12

Has this been fixed already?

**Comment by tejassharma96** [comment]
Nope, but I investigated a bit more and it was an "intended" (probably didn't intend to break the functionality, but an intentional change) breaking change in [this commit](https://github.com/xOnlyFadi/xonlyfadi-extensions/commit/c0d00afba0a9d9ff740e3e097412516df3861974) - changed the type to a string array instead of an `Uploader` array. Probably not much to do here apart from tell people to re-add everything 🤷

**Comment by Ivanmatthew** [comment]
@niclimcy
Can you add backwards compatibility for this?

**Comment by Ivanmatthew** [comment]
> Nope, but I investigated a bit more and it was an "intended" (probably didn't intend to break the functionality, but an intentional change) breaking change in [this commit](https://github.com/xOnlyFadi/xonlyfadi-extensions/commit/c0d00afba0a9d9ff740e3e097412516df3861974) - changed the type to a string array instead of an `Uploader` array. Probably not much to do here apart from tell people to re-add everything 🤷

I might be inclined to create a backwards compatible function for this, but seeing how not that many people have made issues for this, I don’t think it’s an issue at large.

**Comment by niclimcy** [comment]
> @niclimcy Can you add backwards compatibility for this?

Damn i didn't consider backwards compatibility, easiest way is to just reset all settings and re-add honestly.
