### ISSUE TITLE
Log Error Problem 

### ISSUE THREAD

**Issue by 1ambsaucer** [xOnlyFadi/xonlyfadi-extensions#25]
Hi! Encountered an issue with the ReadComicOnline extension where clicking on a comic on the Paperback app would give me a black screen and a log error.

Video:
https://github.com/xOnlyFadi/xonlyfadi-extensions/assets/174855570/198c1a92-3742-4c58-903a-b62918ba8499

I attempted to reinstall the extension, load backups, and log out and log back in multiple times, no fix. Passing captcha on the site didn’t fix the issue either. Updating it from 1.0.7 to 2.0.2 temporarily fixed the issue but it returned a day later. 

App Version: v0.8.7-r12

Source w/ Source Version: ReadComicOnline 2.0.2

**Comment by xOnlyFadi** [comment]
fixed on the newest version.
