### ISSUE TITLE
xOnlyFadi sources not working due to cloudflare error in Paperback

### ISSUE THREAD

**Issue by chailjc** [xOnlyFadi/xonlyfadi-extensions#27]
**Describe the bug**
xOnlyFadi sources will always show error message when opening the app. Bookmarked comics still appear in library but no pages will load.

**To Reproduce**
1. Open Paperback.
2. Click on any xOnlyFadi sources.
3. See error

**Expected behavior**
For error message to stop appearing and for comic to load.

**Screenshots/Video**
![image](https://github.com/user-attachments/assets/548b90ba-735d-4566-8b0e-2bb62d16de43)

**App version**
- v0.8.8 (24)

**Source WITH source version**
- ReadComicOnline 2.0.3

**Additional context**
Webpage still loads and comics can be opened in cloudflare, but not from the app.

**Comment by JotaNimble** [comment]
Same behavior and error with ComicK 2.2.1

**Comment by Denis1611** [comment]
I guess it’s just fu at this point with no answers regarding this… this sucks hard

**Comment by xOnlyFadi** [comment]
Im not with my main computer and Im currently in the usa not in my own country and do not have a computer to code with which currently I cannot fix these two sources once im back ill fix asap.

**Comment by JotaNimble** [comment]
thanks fadi, hope you have a great travel!

**Comment by Denis1611** [comment]
Any update?

**Comment by xOnlyFadi** [comment]
still in america returning on the 17th

**Comment by xOnlyFadi** [comment]
Hello eveybody who was waiting for the rco source the current method to parse the pages is changed very much which which does not work on the current pb version I do not know when which version will make it avaliable so ill remove it indefinetly until they stop playing cat and mouse game
@Denis1611 @chailjc @JotaNimble
