### ISSUE TITLE
[Feature Request] Uploader Priority when using "Chapter Score Filtering"

### ISSUE THREAD

**Issue by ghost** [xOnlyFadi/xonlyfadi-extensions#28]
Hello, I'm a fan of your extensions for Paperback, and I wanted to request a feature for the "ComicK" source. I'd really like a way to prioritize specific Uploaders when using ”Chapter Score Filtering.“ Thank you for your time.

**Comment by niclimcy** [comment]
Will be too overly complicated to implement
