### ISSUE TITLE
Comick new api change, so extension needs update 

### ISSUE THREAD

**Issue by xMikasa** [xOnlyFadi/xonlyfadi-extensions#4]
Going to any manga in comick causes error due to new change made by comick to their code.

https://api.comick.fun/comic/{id}/chapter(deprecated) 

will change to 

https://api.comick.fun/comic/{hid}/chapters

![131136DD-BD48-4E95-8157-4B84015FF450](https://user-images.githubusercontent.com/6782462/227249490-13f2ea75-0371-43a8-ab17-ff64003cb949.jpeg)

**Comment by xOnlyFadi** [comment]
fixed
