### ISSUE TITLE
TuMangaOnline failed to parse

### ISSUE THREAD

**Issue by seitenca** [xOnlyFadi/xonlyfadi-extensions#6]
Sometimes when loading chapters this error happens "failed to parse the chapter..." it's something that it's known and can't be fixed or it's unknown ?

**Comment by Ivanmatthew** [comment]
> Sometimes when loading chapters this error happens "failed to parse the chapter..." it's something that it's known and can't be fixed or it's unknown ?

Fixed with PR #8

**Comment by seitenca** [comment]
Yes, the issue is no longer present, thanks, closing the issue.

**Comment by JoseMoreville** [comment]
This still happens.
